# Generated by Django 5.0.2 on 2024-03-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deleted', 'Deleted')], default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('For Approval', 'Pending'), ('Active', 'Active'), ('Disabled', 'Disabled'), ('Deleted', 'Deleted')], default='Pending', max_length=50),
        ),
    ]
