# Generated by Django 5.0.2 on 2024-03-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0002_alter_roles_status_alter_staff_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Deleted', 'DELETED')], default='ACTIVE', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('For Approval', 'PENDING'), ('Active', 'ACTIVE'), ('Disabled', 'DISABLE'), ('Deleted', 'DELETED')], default='PENDING', max_length=50),
        ),
    ]
