# Generated by Django 5.0.2 on 2024-03-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0003_alter_roles_status_alter_staff_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roles',
            old_name='create_Date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='create_Date',
            new_name='create_date',
        ),
        migrations.AlterField(
            model_name='roles',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Deleted', 'DELETED')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('For Approval', 'PENDING'), ('Active', 'ACTIVE'), ('Disabled', 'DISABLED'), ('Deleted', 'DELETED')], default='PENDING', max_length=50),
        ),
    ]
