# Generated by Django 5.0.2 on 2024-07-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resources', '0004_rename_create_date_roles_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Deleted', 'DELETED')], default='ACTIVE', max_length=50),
        ),
    ]
