# Generated by Django 5.0.2 on 2024-03-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply_request',
            old_name='create_Date',
            new_name='create_date',
        ),
        migrations.RenameField(
            model_name='supply_request',
            old_name='delivered_date',
            new_name='date_delivered',
        ),
        migrations.RenameField(
            model_name='warehouse',
            old_name='create_Date',
            new_name='create_date',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('For Approval', 'PENDING'), ('Active', 'ACTIVE'), ('Disabled', 'DISABLED'), ('Deleted', 'DELETED')], default='PENDING', max_length=50),
        ),
    ]
