# Generated by Django 5.0.2 on 2024-03-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_rename_create_date_supply_request_create_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply_request',
            old_name='drivers_truck',
            new_name='driver_truck',
        ),
    ]
