# Generated by Django 5.0.2 on 2024-03-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_rename_drivers_truck_supply_request_driver_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('Active', 'ACTIVE'), ('Deleted', 'DELETED')], default='PENDING', max_length=50),
        ),
    ]
