# Generated by Django 5.0.2 on 2024-04-18 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resources', '0001_initial'),
        ('products', '0001_initial'),
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='In_Out',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_in', models.BooleanField()),
                ('create_date', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inv_no', models.IntegerField()),
                ('date', models.DateField()),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('For Approval', 'PENDING'), ('Active', 'ACTIVE'), ('Disabled', 'DISABLED'), ('Deleted', 'DELETED')], default='PENDING', max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('entry_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='human_resources.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('in_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches_others.in_out')),
                ('stock_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
                ('stock_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('stock_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.warehouse')),
            ],
        ),
    ]
