# Generated by Django 5.0.2 on 2024-07-06 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inv_no', models.IntegerField()),
                ('date', models.DateField()),
                ('total_price', models.FloatField()),
                ('entry_by', models.CharField(max_length=110)),
                ('status', models.CharField(choices=[('For Approval', 'PENDING'), ('Active', 'ACTIVE'), ('Disabled', 'DISABLED'), ('Deleted', 'DELETED')], default='PENDING', max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('stock_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supply_chain.warehouse')),
            ],
        ),
    ]
