# Generated by Django 5.0.2 on 2024-07-07 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches_others', '0001_initial'),
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='stock_warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supply_chain.warehouse'),
        ),
    ]
