# Generated by Django 5.0.2 on 2024-07-07 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches_others', '0002_alter_stocks_stock_warehouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='stock_warehouse',
            new_name='warehouse',
        ),
    ]
