# Generated by Django 5.0.2 on 2024-07-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches_others', '0003_rename_stock_warehouse_stocks_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
