# Generated by Django 5.0.2 on 2024-04-18 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_out',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField()),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('in_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.in_out')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('stock_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
            ],
        ),
    ]
