# Generated by Django 5.0.2 on 2024-03-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
