# Generated by Django 5.0.2 on 2024-04-18 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_alter_in_out_create_date_stocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocks',
            old_name='product',
            new_name='stock_product',
        ),
    ]
