# Generated by Django 5.0.2 on 2024-04-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_rename_product_stocks_stock_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='in_out',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='entry_by',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='stock_category',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='stock_product',
        ),
        migrations.DeleteModel(
            name='In_Out',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
