# Generated by Django 5.0.2 on 2024-03-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_alter_branches_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='status',
            field=models.CharField(choices=[('For Approval', 'Pending'), ('Active', 'Active'), ('Disabled', 'Disabled'), ('Deleted', 'Deleted')], default='Pending', max_length=50),
        ),
    ]
