# Generated by Django 5.0.2 on 2024-03-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0006_alter_branches_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='status',
            field=models.CharField(choices=[('For Approval', 'PENDING'), ('Active', 'ACTIVE'), ('Disabled', 'DISABLED'), ('Deleted', 'DELETED')], default='PENDING', max_length=50),
        ),
    ]
