# Generated by Django 5.0.2 on 2024-04-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='product_category',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='package',
            new_name='product_package',
        ),
        migrations.RemoveField(
            model_name='items',
            name='products',
        ),
    ]
